#! /usr/bin/env bash

pushd $HOME/tesi

[ ! -d "./data/milan" ] && mkdir -p ./data/milan

echo "Retrieving Municipi (.geojson)"
curl "https://dati.comune.milano.it/dataset/36ba21c2-8b48-43ce-bbe1-e236a8a49ff6/resource/99ecd085-0b04-4fb2-a66e-9795694d4fc4/download/ds379_municipi_label.geojson" \
    -o ./data/milan/milan_municipi.geojson

echo -e "\nRetrieving Municipi (.csv)"
curl "https://dati.comune.milano.it/dataset/36ba21c2-8b48-43ce-bbe1-e236a8a49ff6/resource/ebb1e5e3-fde1-46dd-8501-fa03ecb5d4bf/download/ds379_municipi_label_4326.csv" \
    -o ./data/milan/milan_municipi.csv

echo -e "\nRetrieving NILs (.geojson)"
curl "https://dati.comune.milano.it/dataset/e8e765fc-d882-40b8-95d8-16ff3d39eb7c/resource/9c4e0776-56fc-4f3d-8a90-f4992a3be426/download/ds964_nil_wm.geojson" \
    -o ./data/milan/milan_nil.geojson

echo -e "\nRetrieving NILs (.csv)"
curl "https://dati.comune.milano.it/dataset/e8e765fc-d882-40b8-95d8-16ff3d39eb7c/resource/3fce7202-0076-4a7b-ac2c-d2ab9b5dc658/download/ds964_nil_wm_4326.csv" \
    -o ./data/milan/milan_nil.csv