#! /usr/bin/env bash

# import variables for making colored output easier
source "./formatting_colors"

#checks if the server is running
if [[ "$(pg_ctl status)" == "pg_ctl: no server running" ]]; then
    echo -e "\n${BOLD}${RED}==> Postgres server is not running, starting the server...${RESET}"
    # starts the server, deletes output
    pg_ctl start -D /usr/local/var/postgres > /dev/null 2>&1
else
    echo -e "\n${CYAN}${BOLD}==> Postgres server is already running.${RESET}"
fi

# lists where postgres binary and server location are
PG_STATUS=$(pg_ctl status -D /usr/local/var/postgres | sed "s/\"//g" |  awk "NR==2")

echo -e "\n${BOLD}${WHITE}PostgreSQL binary:${BLUE}$(echo "$PG_STATUS" | awk 'BEGIN { FS = " " } ; {print $1}')${RESET}
${BOLD}${WHITE}Server directory:${BLUE}$(echo "$PG_STATUS" | awk 'BEGIN { FS = " " } ; {print $3}')${RESET}"
