#! /usr/bin/env bash

EXEC_DIR=${1:-"$HOME/tesi/notebooks"}

pushd "$EXEC_DIR" 1>/dev/null || exit

echo -e "Trusting notebooks in $EXEC_DIR\n"

for NOTEBOOK in *.ipynb ; do
    jupyter trust "$NOTEBOOK"
    done

popd 1>/dev/null || exit