---
jupyter:
  jupytext:
    formats: notebooks///ipynb,notebooks_r///Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.11.4
  kernelspec:
    display_name: Forecasting Bikemi
    language: python
    name: bikemi
---

# Import Libraries, Load Data and Generate Features

```{python}
import pandas as pd
import plotly.express as px
pd.options.plotting.backend = "plotly"

# import custom functions
import custom_functions.time_series_analysis as tsa
import custom_functions.plot_styles as ps

ps.matplotlib_styles()
```

```{python}
df = pd.read_csv(
    "../data/bikemi_csv/daily_outflow.csv",
    parse_dates=[0],
    index_col=[0]
)

daily_outflow = tsa.create_ts_features(
    df, features=["day", "week", "month", "weekends", "holidays"]
)

daily_outflow.head()
```

# Visualise the data



## Time Series Line Plot

```{python}
ts_plot = daily_outflow.plot(
    y="count",
    title="Daily BikeMi Rentals (2019)",
    color_discrete_sequence=px.colors.qualitative.T10,
    labels = {
        "count": "Rentals ",
        "giorno_partenza" : "Date ",
    }
)

ps.plotly_style(ts_plot)
```

The first thing that comes to mind is that the series displays a great variance. Clearly, the data is non-stationary: we see strong seasonal patterns. These are likely due to weekends and holidays. We can clearly see a trend, where the trip number increases until the middle of the year and then starts decreasing, reaching its lowest in the colder winter months. Let's explore them.


## Histograms

```{python}
hist_weekends = daily_outflow.plot.bar(
    x = daily_outflow.index,
    y = "count",
    title="BikeMi Rentals against Weekends (2019)",
    color = "is_weekend",
    color_discrete_sequence=px.colors.qualitative.Pastel,
    labels = {
        "count": "Rentals ",
        "giorno_partenza" : "Date ",
        "is_weekend": "Weekend "
    }
)

ps.plotly_style(hist_weekends)
```

```{python}
hist_holidays = daily_outflow.plot.bar(
    x = daily_outflow.index,
    y = "count",
    title="Bikemi Rentals against Holidays (2019)",
    color = "holiday",
    color_discrete_sequence=px.colors.qualitative.Vivid,
    labels = {
        "count": "Rentals ",
        "giorno_partenza" : ""
    }
)

ps.plotly_style(hist_holidays)
```

## Rolling Statistics


We can plot rolling means to get a better sense of these fluctuations.

```{python}
# inspect values with `fig.data`
tsa.px_rolling_statistics(
    ts = daily_outflow,
    col = "count",
    lags = 7,
    statistics=["mean", "std"]
)
```

```{python}
tsa.px_rolling_statistics(
    ts = daily_outflow,
    col = "count",
    lags = 30,
    statistics=["mean", "std"]
)
```

We could plot the individual values for each month to display the difference in values. However, we can show these features better with a boxplot:


## Seasonality Boxplots

```{python}
tsa.subunits_boxplot(daily_outflow["count"], y = "count", time_subunit = "month")
```

However, the most important source of variation clearly is the weekly seasonality. The boxplot function is designed to accept various time formats, so we can adapt it pretty quickly:

```{python}
tsa.subunits_boxplot(daily_outflow["count"], y = "count", time_subunit = "weekday")
```
